### ISSUE TITLE
Pouvoir scroller automatiquement jusqu'au titre qu'on vient d'ajouter

### ISSUE THREAD

**Issue by atm-gauthier** [ATM-Consulting/dolibarr_module_subtotal#115]
Comme sur un ajout de ligne sur dolibarr, il serait idéal que lorsqu'on ajoute un titre ou un ST, ça nous ramène directement jusqu'en bas de la page.

**Comment by atm-alexis** [comment]
module scrollto

**Comment by atm-gauthier** [comment]
Thanks je l'ai dit au client
