### ISSUE TITLE
Break page do not work corretly

### ISSUE THREAD

**Issue by FHenry** [ATM-Consulting/dolibarr_module_subtotal#12]
I've got a problem on break page when title line in just on the end of a page I send you by email the PDF result.
If I uncomment line 604-612 into class/actions_subtotal.class.php it works, Why this code is commented if it work ?
I'm on a Dolibarr 3.5, may be break page feature in newer dolibarr version do the tricks and that why you comment this code because it is no more usefull ?

**Comment by atm-alexis** [comment]
hi, don't remember exactly why but i don't think it's work all time. The matters come from the dolibarr action on break page in each model. Never find the good way for all cases (it's why i introduce the manual page break). 

If it's work to you all time, plz PR it in few days (to be sure). May be i find the way without understand it ;-)

**Comment by FHenry** [comment]
I've already break my brain on this break pages stuff, on Ultimate PDF module, i've debug with @grandoc but it's tricky all the time.
I've done unit test with uncomment code, and it seems to work. Let's my custmer use it and I will do a PR
