### ISSUE TITLE
Unwanted numbers in columns on titles with Dolibarr 3.7

### ISSUE THREAD

**Issue by rdoursenaud** [ATM-Consulting/dolibarr_module_subtotal#15]
Columns should be empty
![capture d ecran de 2015-11-25 12-42-31](https://cloud.githubusercontent.com/assets/1210367/11396502/32f3718a-9372-11e5-95bd-edd3b5d4ce02.png)

Behavior is OK with Dolibarr 3.8…

**Comment by atm-alexis** [comment]
Yep, it's Fixed

**Comment by rdoursenaud** [comment]
Thanks :)
