### ISSUE TITLE
Hidding details and prices prevents VAT total from being displayed

### ISSUE THREAD

**Issue by rdoursenaud** [ATM-Consulting/dolibarr_module_subtotal#20]
Dolibarr version: 3.8.2
Module version: 1.6.0
Setup: Hide details, Hide prices

The VAT total(s) are missing!

**Comment by rdoursenaud** [comment]
The patch you sent didn't solve the problem.
Please have another look.

**Comment by atm-alexis** [comment]
Try it on 3.8, i can't reproduct the bug...

**Comment by rdoursenaud** [comment]
Please have a look at our demo instance (login: demo, pass: demo).
https://demo.zenfusion.fr/compta/facture.php?facid=265
There's a product with 5.5% VAT and another with 20% VAT.
https://demo.zenfusion.fr/document.php?modulepart=facture&file=FA1601-0182%2FFA1601-0182.pdf
And yet, no VAT total is displayed.
If you regenerate the document without hiding lines, VAT totals are displayed.

**Comment by atm-alexis** [comment]
Ok, understand, missmatch the good option. I known it's due to the Dolibarr Core, i think with 3.9 (and patched 3.8) we can do something for that, i will looking it

**Comment by atm-ph** [comment]
This issue have been fixed with the subtotal PDF
