### ISSUE TITLE
Problème avec conf expérimentale "Avoir une seule ligne de titre + total"

### ISSUE THREAD

**Issue by atm-gauthier** [ATM-Consulting/dolibarr_module_subtotal#205]
Donne des rendus du type :
![image](https://user-images.githubusercontent.com/5585819/120651916-92570800-c47f-11eb-968f-0a60eed0fc6c.png)

**Comment by atm-john** [comment]
Cette conf est a supprimé je pense car elle est expérimental depuis toujours... elle n'a jamais suivie les evols
