### ISSUE TITLE
API Documents /Buildoc et subtotal

### ISSUE THREAD

**Issue by dNicolle** [ATM-Consulting/dolibarr_module_subtotal#210]
Bonjour,

Lorsqu'on génère un document depuis l'API documents/buildoc, les lignes titre, texte et sous-total ne se "transforment" pas comme lorsqu'on passe par le bouton générer dans l'interface d'administration.

Avez-vous une piste pour m'aider à faire fonctionner cela ?
Cordialement,
Dominique

**Comment by atm-john** [comment]
Bonjour, il faut enregistrer les lignes de la même manière que le fait le module probablement.
