### ISSUE TITLE
Coloration ligne de titre et ligne de total

### ISSUE THREAD

**Issue by gdesnoues** [ATM-Consulting/dolibarr_module_subtotal#215]
Ajouter la possibilité de colorer la ligne de titre et la ligne de total via 2 constantes
SUBTOTAL_TITLE_BACKGROUNDCOLOR et SUBTOTAL_SUBTOTAL_BACKGROUNDCOLOR

J'ai un bout de code fonctionnel que je peux passer en PR si vous le souhaitez

#216

**Comment by gdesnoues** [comment]
> Merci,
> 
> Je vous invite à nous faire une PR ;-)
> 
> Bonne journée.

PR faite.
À voir s’il faut compléter certains autres endroits du code.
C'est ma première PR et première modif sur code Dolibarr 😉

**Comment by atm-john** [comment]
#216
