### ISSUE TITLE
Problème d'accès à la page de configuration

### ISSUE THREAD

**Issue by adonix-dev** [ATM-Consulting/dolibarr_module_subtotal#234]
Bonjour,
Nous utilisons actuellement la version 14.0.5 de Dolibarr.
Il se trouve que j'arrive bien à activer le module malgrès une erreur de token en désactivant un check CSRFCHECK_WITH_TOKEN dans admin/modules.php.
Néanmoins, impossible d'acceder à la page de configuration du module. L'accée à l'url "/subtotal/admin/subtotal_setup.php" n'envoit pas d'erreur mais affiche le dashboard de Dolibarr.

**Comment by atm-john** [comment]
Bonjour,

Merci de l’intérêt porté à nos modules.
Nous ne faisons pas d'assistance sur les issues de gitHub.
Vous pouvez cependant faire une demande sur [Contact ATM Dolistore](https://www.atm-consulting.fr/contact-dolibarr/dolistore-contactez-nous/).

Bonne journée
