### ISSUE TITLE
Reférence externe de ligne supprimée

### ISSUE THREAD

**Issue by EchoLoGeek** [ATM-Consulting/dolibarr_module_subtotal#276]
Lors de l'utilisation du formulaire d'édition par bloc de lignes, les informations contenues dans le champ "ref_ext" sont supprimées.
Edition d'une facture de situation et du pourcentage d'avancement d'un bloc de lignes en l'occurrence ici.

**Comment by atm-florianm** [comment]
J'ai essayé de reproduire le problème, mais je manque d'infos (éventuels autres modules installés, cas de reproduction pas à pas…) et n'ai pas pu déterminer s'il était encore présent. Je clôture l'issue, mais n'hésitez pas à la rouvrir si le problème existe encore.
