### ISSUE TITLE
Display price and total round

### ISSUE THREAD

**Issue by rycks** [ATM-Consulting/dolibarr_module_subtotal#312]
Default settings seems to be in a race condition:

![image](https://user-images.githubusercontent.com/1468823/218593420-a25f667d-2d08-452a-a34c-2abbf849c751.png)

**Comment by atm-john** [comment]
Hi,

Just configure your Dolibarr...

best regards

**Comment by rycks** [comment]
hey john,
excuse me i don't put a full screenshot but all others lines are well handle but not subtotal.

Then i don't loose my time to open tickets in that sort of case ... there is really a race condition in that plugin where prices do not respect dolibarr settings

![image](https://user-images.githubusercontent.com/1468823/220071117-56cc548d-1b7e-4649-9e6b-aa50ce89759d.png)

**Comment by atm-john** [comment]
see https://github.com/ATM-Consulting/dolibarr_module_subtotal/pull/317
