### ISSUE TITLE
Coquille Orthographe

### ISSUE THREAD

**Issue by ldennery** [ATM-Consulting/dolibarr_module_subtotal#378]
Bonjour l'équipe ATM,
juste pour vous signaler une coquille orthographique dans le fichier de langue FR

SubtotalSetup = Paramettre module sous total
SubTotalSetupPage = Paramettre module sous total

Paramètre ne prend qu'un seul "t"
Merci pour ces supers modules !

**Comment by atm-john** [comment]
Thanks
