### ISSUE TITLE
Amélioration : calcul total des remises

### ISSUE THREAD

**Issue by Mavyre** [ATM-Consulting/dolibarr_module_subtotal#394]
Bonjour ATM !

Tout d'abord, merci pour ce super module !

Il y a quelques versions maintenant, Dolibarr a ajouté la possibilité d'afficher sur les factures le "Total avant remise" et "Total des remises". Malheureusement, il semblerait que Dolibarr n'arrive pas à compter les remises quand elles sont sous un sous-total. 

Voici le snippet utilisé par le modèle Sponge pour compter les remises :
```php
// Total remise
$total_line_remise = 0;
foreach ($object->lines as $i => $line) {
	$resdiscount = pdfGetLineTotalDiscountAmount($object, $i, $outputlangs, 2);
	$total_line_remise += (is_numeric($resdiscount) ? $resdiscount : 0);
	// Gestion remise sous forme de ligne négative
	if ($line->total_ht < 0) {
		$total_line_remise += -$line->total_ht;
	}
}
```

J'ai du mal à voir ce que contient réellement `$object->lines` dans le cas où on utilise subtotal.

Quelqu'un a une idée du comment du pourquoi ? Est-ce que c'est côté subtotal ou sponge qu'il faut fixer quelque chose ?

**Comment by Mavyre** [comment]
J'ai diagnostique le soucis. Il vient principalement du fait que la fonction `pdfGetLineTotalDiscountAmount` (incluse dans `pdf.lib.php`) ait un calcul un peu particulier pour compter les réductions. 

Il utilise le prix unitaire multiplié par la quantité, puis en soustrait le prix final. Ça donne effectivement la réduction pour une ligne donnée.
Sauf que, les lignes constituant les sous totaux ont un prix unitaire nul et une quantité à 99. Dans ce cas là, la fonction retourne l'opposé du sous-total (si le sous-total est de 100,  `pdfGetLineTotalDiscountAmount` retourne -100).
On arrive alors à un `$total_line_remise` négatif, et non pris en compte par les modèles de facture.

Pour fixer ça rapidement, il suffit de modifier le `pdf.lib.php` et de retourner 0 à la place d'un nombre négatif : 
```php
return max(0, $sign * (($object->lines[$i]->subprice * $object->lines[$i]->qty) - $object->lines[$i]->total_ht));
```

Je pense que ça doit être fixé dans le core de Dolibarr, puisque je ne vois pas comment le fixer dans le module subtotal directement...

**Comment by atm-john** [comment]
Bonjour merci pour l'information et les recherches.

**Comment by atm-florianm** [comment]
J'ai ouvert un ticket interne pour qu'on corrige ce bug.

**Comment by atm-quentin** [comment]
Bonjour,

Le retour a été traité dans les branches 3.23 et main.
Merci de votre retour
Cordialement,
