### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by rdoursenaud** [ATM-Consulting/dolibarr_module_subtotal#5]
Adding a title brings a native modal window from the browser.

This is disruptive, distracting and not very well integrated.
The fact that it's modal prevents me from using another tab at the same time.
I think it would be much better to use a jQuery (dolibarr native) modal popup instead.

**Comment by atm-maxime** [comment]
Feedback from another user, related to this, he suggest to be able to specify the page break directly while creating the title. Jquery modal popup will allow that.

**Comment by rdoursenaud** [comment]
:+1:

**Comment by rdoursenaud** [comment]
In e36956b83922fc1ecc89f893f35203e7e979e349 :+1:
