### ISSUE TITLE
Affichage barre de titre de lignes des contenu

### ISSUE THREAD

**Issue by RomainDeschamps** [ATM-Consulting/dolibarr_module_subtotal#53]
dolibarr 5.0.1 :
![image](https://cloud.githubusercontent.com/assets/11922840/25893175/206ebed6-3577-11e7-82d2-cac03f25da9a.png)

dolibarr 5.0.2 :
![image](https://cloud.githubusercontent.com/assets/11922840/25893161/0f0e825c-3577-11e7-8659-6b4d5ec71943.png)

**Comment by atm-arnaud** [comment]
La colonne Prix de revient à disparu. Ceci est volontaire ? Car le soucis provient surement de cette configuration.

**Comment by patas-monkey** [comment]
Yep. Tout revient en ordre en affichant les éléments du module marge...
On a donc un p'tit souci d'affichage si on choisit de ne pas les afficher.
