### ISSUE TITLE
pouvoir saisir un texte repris automatiquement sur titre et ss total

### ISSUE THREAD

**Issue by atm-berengere** [ATM-Consulting/dolibarr_module_subtotal#93]
si on souhaite avoir un texte qui soit repris automatiquement  dans tous les titre ou tous les totaux des propales, factures etc....
avec possibilités de modifier / complété / effacé

**Comment by atm-ph** [comment]
Peux tu expliciter la demande ? J'ai l'impression que tu parles simplement d'un ctrl+c et ctrl+v
